export const state = {
    activeTab: 'members',
    activeModules: null,
    departments: [],
    selectedDept: '',
    members: [],
    loading: false,
    configLoading: false,
    error: '',
    overview: null,
    overviewLoading: false,
    overviewError: '',
    overviewExpanded: {},
    search: '',
    sortCol: 'familyName',
    sortDir: 'asc',
    colMenuOpen: false,
    settings: null,
    calYear: new Date().getFullYear(),
    calMonth: new Date().getMonth() + 1,
    calEvents: [],
    calCalendars: [],
    calEnabled: {},
    calLoading: false,
    calError: '',
    calView: 'month',
    inventoryTab: 'items', // 'items', 'groups', 'locations'
    inventoryData: null,
    inventoryLoading: false,
    inventoryError: '',
    financeTab: 'overview',
    financeOverview: null,
    financeOverviewLoading: false,
    financeOverviewError: '',
    financeAccounts: [],
    financeAccountsLoading: false,
    financeAccountsError: '',
    financeSelectedAccountID: 0,
    financeBookings: [],
    financeBookingsLoading: false,
    financeBookingsError: '',
    financeBookingSearch: '',
    financeBookingDateFrom: (() => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`; })(),
    financeBookingDateTo: new Date().toISOString().slice(0,10),
    financeInvoices: [],
    financeInvoicesLoading: false,
    financeInvoicesError: '',
    financeInvoiceSearch: '',
    expandedInvoiceID: null,
    invoiceItems: {},
    invoiceItemsLoading: {},
    cashPaymentModal: null,
    cashPaymentLoading: false,
    cashPaymentError: '',
    columns: [
        { key: 'membershipNumber', label: 'Nr.',           visible: true  },
        { key: 'familyName',       label: 'Nachname',      visible: true  },
        { key: 'firstName',        label: 'Vorname',       visible: true  },
        { key: 'age',              label: 'Alter',         visible: true  },
        { key: 'dateOfBirth',      label: 'Geburtsdatum',  visible: true  },
        { key: 'email',            label: 'E-Mail',        visible: true  },
        { key: 'phone',            label: 'Telefon',       visible: false },
        { key: 'mobile',           label: 'Mobil',         visible: false },
        { key: 'street',           label: 'Straße',        visible: false },
        { key: 'zip',              label: 'PLZ',           visible: false },
        { key: 'city',             label: 'Stadt',         visible: false },
        { key: 'joinDate',         label: 'Eintritt',      visible: false },
        { key: 'resignationDate',  label: 'Austritt',      visible: false },
        { key: 'groups',           label: 'Gruppen',       visible: false },
        { key: 'groupShorts',      label: 'Kürzel',        visible: true  },
    ],
};

export const PAGE_TITLES = {
    overview: 'Abteilungen',
    members:  'Mitglieder',
    finance:  'Finanzen',
    calendar: 'Kalender',
    inventory: 'Inventar',
    settings: 'Einstellungen',
};
