// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCalendarEvents(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCalendarEvents'](arg1, arg2, arg3);
}

export function GetCalendars() {
  return window['go']['main']['App']['GetCalendars']();
}

export function GetDepartmentOverview() {
  return window['go']['main']['App']['GetDepartmentOverview']();
}

export function GetDepartments() {
  return window['go']['main']['App']['GetDepartments']();
}

export function GetMembers(arg1) {
  return window['go']['main']['App']['GetMembers'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function ReloadMembers(arg1) {
  return window['go']['main']['App']['ReloadMembers'](arg1);
}
