// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCashPayment(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateCashPayment'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExportMembersExcel(arg1) {
  return window['go']['main']['App']['ExportMembersExcel'](arg1);
}

export function ExportPublicKey() {
  return window['go']['main']['App']['ExportPublicKey']();
}

export function GetBankAccounts(arg1) {
  return window['go']['main']['App']['GetBankAccounts'](arg1);
}

export function GetBookings(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBookings'](arg1, arg2, arg3);
}

export function GetCalendarEvents(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCalendarEvents'](arg1, arg2, arg3);
}

export function GetCalendars() {
  return window['go']['main']['App']['GetCalendars']();
}

export function GetDepartmentOverview() {
  return window['go']['main']['App']['GetDepartmentOverview']();
}

export function GetDepartments() {
  return window['go']['main']['App']['GetDepartments']();
}

export function GetFinanceOverview(arg1) {
  return window['go']['main']['App']['GetFinanceOverview'](arg1);
}

export function GetInvoiceItems(arg1) {
  return window['go']['main']['App']['GetInvoiceItems'](arg1);
}

export function GetMembers(arg1) {
  return window['go']['main']['App']['GetMembers'](arg1);
}

export function GetOpenInvoices(arg1) {
  return window['go']['main']['App']['GetOpenInvoices'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function ReloadMembers(arg1) {
  return window['go']['main']['App']['ReloadMembers'](arg1);
}

export function ReloadOpenInvoices(arg1) {
  return window['go']['main']['App']['ReloadOpenInvoices'](arg1);
}
