// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCashPayment(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function ExportMembersExcel(arg1:string):Promise<string>;

export function ExportPublicKey():Promise<string>;

export function GetBankAccounts(arg1:string):Promise<Array<main.BankAccountInfo>>;

export function GetBookings(arg1:number,arg2:string,arg3:string):Promise<Array<main.BookingRow>>;

export function GetCalendarEvents(arg1:string,arg2:number,arg3:number):Promise<Array<main.CalendarEvent>>;

export function GetCalendars():Promise<Array<main.CalendarInfo>>;

export function GetDepartmentOverview():Promise<Array<main.DepartmentDetail>>;

export function GetDepartments():Promise<Array<string>>;

export function GetFinanceOverview(arg1:string):Promise<main.FinanceOverview>;

export function GetInventoryOverview():Promise<main.CachedData_main_InventoryOverview_>;

export function GetInvoiceItems(arg1:number):Promise<Array<main.InvoiceItemRow>>;

export function GetMembers(arg1:string):Promise<main.CachedData___main_MemberRow_>;

export function GetOpenInvoices(arg1:string):Promise<main.CachedData___main_InvoiceRow_>;

export function GetSettings():Promise<main.Settings>;

export function ReloadConfig():Promise<main.Settings>;

export function ReloadInventory():Promise<main.CachedData_main_InventoryOverview_>;

export function ReloadMembers(arg1:string):Promise<main.CachedData___main_MemberRow_>;

export function ReloadOpenInvoices(arg1:string):Promise<main.CachedData___main_InvoiceRow_>;
