// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDepartments():Promise<Array<string>>;

export function GetMembers(arg1:string):Promise<Array<main.MemberRow>>;

export function GetSettings():Promise<main.Settings>;

export function ReloadMembers(arg1:string):Promise<Array<main.MemberRow>>;
