// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDepartments() {
  return window['go']['main']['App']['GetDepartments']();
}

export function GetMembers(arg1) {
  return window['go']['main']['App']['GetMembers'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ReloadMembers(arg1) {
  return window['go']['main']['App']['ReloadMembers'](arg1);
}
